name: Nix Build

on:
  push:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0 https://github.com/actions/checkout/releases/tag/v3.6.0
        with:
          ssh-key: ${{ secrets.WORKFLOW_SSH_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@65d7c888b2778e8cf30a07a88422ccb23499bfb8 # v4 https://github.com/DeterminateSystems/nix-installer-action/releases/tag/v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@53b6b26c21172d05af1bbc39e3fb6facd7140272 # v1 https://github.com/DeterminateSystems/magic-nix-cache-action/releases/tag/v1

      - name: Build Aiken
        shell: bash
        run: |
          set +e
          nix build
          exitcode="$?"
          if [[ "$exitcode" != "0" ]] ; then
            echo "::warning::Nix build failed with exit code $exitcode"
            exit 0
          else
            exit "$exitcode"
          fi
