name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8 https://github.com/Swatinem/rust-cache/releases/tag/v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          key: ${{ runner.os }}-cache-build-v${{ inputs.cache-version }}
      - name: Build release
        run: |
          sudo apt-get install -y pkg-config libssl-dev musl musl-dev musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo install --path=crates/aiken --target=x86_64-unknown-linux-musl
          mv $(which aiken) aiken
          ldd aiken
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2 https://github.com/actions/upload-artifact/releases/tag/v4.6.2
        with:
          name: aiken-${{ github.sha }}-${{ runner.arch }}-${{ runner.os }}
          path: ./aiken

  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8 https://github.com/Swatinem/rust-cache/releases/tag/v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          key: ${{ runner.os }}-cache-build-v${{ inputs.cache-version }}
      - name: Run examples
        run: |
          cargo run -r -- check examples/hello_world
          cargo run -r -- check examples/gift_card
      - name: Run acceptance tests
        working-directory: examples/acceptance_tests
        run: |
          cargo install cbor-diag-cli
          bash ci
        shell: bash

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8 https://github.com/Swatinem/rust-cache/releases/tag/v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          key: ${{ runner.os }}-cache-tests-v${{ inputs.cache-version }}
      - name: Run unit tests
        run: cargo test --verbose --workspace

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8 https://github.com/Swatinem/rust-cache/releases/tag/v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          key: ${{ runner.os }}-cache-build-v${{ inputs.cache-version }}
      - name: Run benchmarks
        run: |
          cargo run -r -- check benchmarks

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8 https://github.com/Swatinem/rust-cache/releases/tag/v2.7.8
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          key: ${{ runner.os }}-cache-unit-v${{ inputs.cache-version }}
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
